{% set name = "google-cloud-aiplatform" %}
{% set version = "1.91.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: b14e5e52b52b6012c7dc253beab34c511fdc53c69b13f436ddb06882c1a92cd7

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv --use-pep517
  entry_points:
    - tb-gcp-uploader=google.cloud.aiplatform.tensorboard.uploader_main:run_main

requirements:
  host:
    - python
    - pip !=25.1
    - setuptools
    - wheel
  run:
    - python
    - google-api-core >=1.34.1,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0
    - proto-plus >=1.22.3,<2.0.0
    - protobuf >=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - packaging >=14.3
    - google-cloud-storage >=1.32.0,<3.0.0
    - google-cloud-bigquery-core >=1.15.0,<4.0.0,!=3.20.0
    - google-cloud-resource-manager >=1.3.3,<3.0.0
    - shapely <3.0.0
    - pydantic <3
    - typing_extensions
    - docstring_parser <1

# list tests to be skipped
{% set tests_to_skip = "" %}
# test_admit for numerical approximation error
{% set tests_to_skip = tests_to_skip + " test_admit" %}
{% set tests_to_skip = tests_to_skip + " or test_function_call" %}
{% set tests_to_skip = tests_to_skip + " or test_batch_predict_job_done_create" %}
{% set tests_to_skip = tests_to_skip + " or test_function_response" %}
# skip the whole class because it is not able to mock the GCS access correctly
{% set tests_to_skip = tests_to_skip + " or TestGcsUtils" %}
# results in "gs:////" instead of "gs://""
{% set tests_to_skip = tests_to_skip + " or test_image_embedding_model_with_storage_url" %}
# requires pyarrow which will cause conflicts
{% set tests_to_skip = tests_to_skip + " or test_create_dataset_tabular_from_dataframe" %}
# wrong positional index in a list, same items
{% set tests_to_skip = tests_to_skip + " or test_get_experiment_df" %}
{% set tests_to_skip = tests_to_skip + " or test_compute_multiple_metrics" %}
# write permission error on win
{% set tests_to_skip = tests_to_skip + " or test_package_folder" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_package_file" %}  # [win]
# list test files to be ignored
{% set tests_to_ignore = "" %}
# noxfile.py#L205-L207
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/architecture" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/vertex_langchain" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/vertex_ray" %}
# they require docker, some docker functionalities
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_prediction.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_docker_utils.py" %}
# ModuleNotFoundError: No module named google-vizier
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_vizier.py" %}
# ModuleNotFoundError: No module named explainable_ai_sdk
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_logdir_loader.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_explain_lit.py" %}
# ModuleNotFoundError: No module named mlflow
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_autologging.py" %}
# ModuleNotFoundError: No module named tensorboard
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_uploader.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_uploader_utils.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_cloud_profiler.py" %}
# ModuleNotFoundError: No module named tensorflow
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_models.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_uploader_main.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_metadata_models.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_explain_saved_model_metadata_builder_tf1_test.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_explain_saved_model_metadata_builder_tf2_test.py" %}
# ModuleNotFoundError: No module named llama_index
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/vertex_llama_index/test_reasoning_engine_templates_llama_index.py" %}
# ModuleNotFoundError: No module named distutils
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_training_jobs.py" %}
# ModuleNotFoundError: No module named 'google.adk'
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/vertex_adk/test_reasoning_engine_templates_adk.py" %}
# ModuleNotFoundError: No module named 'openinference-instrumentation-autogen'
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/vertex_ag2/test_agent_engine_templates_ag2.py" %}
# this requires directly google-cloud-bigquery-storage and if we add it in the test environment
# will cause other conflicts
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_featurestores.py" %}
# flaky fails
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_upload_tracker.py" %}

test:
  source_files:
    - tests/unit
  imports:
    - google
    - google.cloud
    - google.cloud.aiplatform
    - google.cloud.aiplatform_v1
    - google.cloud.aiplatform_v1beta1
    - vertexai
    - vertexai
    - vertexai._model_garden
    - vertexai.agent_engines
    - vertexai.agent_engines.templates
    - vertexai.batch_prediction
    - vertexai.caching
    - vertexai.evaluation
    - vertexai.evaluation.metrics
    - vertexai.example_stores
    - vertexai.extensions
    - vertexai.generative_models
    - vertexai.language_models
    - vertexai.model_garden
    - vertexai.preview
    - vertexai.preview.evaluation
    - vertexai.preview.rag
    - vertexai.preview.rag.utils
    - vertexai.preview.reasoning_engines
    - vertexai.preview.tuning
    - vertexai.prompts
    - vertexai.rag
    - vertexai.rag.utils
    - vertexai.reasoning_engines
    - vertexai.resources
    - vertexai.resources.preview
    - vertexai.tokenization
    - vertexai.tuning
    - vertexai.vision_models
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # tb-gcp-uploader needs tensorflow, and all these requirements, which are not all available:
    # tensorflow 2.4.1 has requirement absl-py >=0.10,<11
    # tensorflow 2.4.1 has requirement flatbuffers~=1.12.0
    # tensorflow 2.4.1 has requirement grpcio~=1.32.0
    # tensorflow 2.4.1 has requirement tensorflow-estimator<2.5.0,>=2.4.0
    # tensorflow 2.4.1 has requirement typing-extensions~=3.7.4
    # - tb-gcp-uploader --helpshort
    # Tests works locally on win, linux, and osx. More than 150,000 test needs 5 hour to build. Just skip.
    # - pytest -vv tests/unit {{ tests_to_ignore }} -k "not ({{ tests_to_skip }})"
  requires:
    # latest pip 25.1 is broken
    - pip 25.0
    - pytest
    - mock
    - pytest-asyncio
    - pytest-xdist
    - pandas
    - tqdm
    - scikit-learn
    - sentencepiece
    - pyyaml
    - pillow
    - jsonschema
    - ruamel.yaml
    - requests-toolbelt
    - ipython
    - opentelemetry-sdk <2
    - jinja2

about:
  home: https://cloud.google.com/vertex-ai/docs
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: A Python SDK for Vertex AI, a fully managed, end-to-end platform for data science and machine learning.
  description: |
    Vertex AI: Google Vertex AI is an integrated suite of machine learning tools and services
    for building and using ML models with AutoML or custom code. It offers both novices and
    experts the best workbench for the entire machine learning development lifecycle.
  doc_url: https://cloud.google.com/python/docs/reference/aiplatform/latest
  dev_url: https://github.com/googleapis/python-aiplatform
  
extra:
  recipe-maintainers:
    - xylar
  skip-lints:
    - missing_test_requirement_pip
