{% set name = "google-cloud-aiplatform" %}
{% set version = "1.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-aiplatform-{{ version }}.tar.gz
  sha256: 1ea343077373da116b65f708103202f07733b1904e9465250407a2fd6a28180b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python
    - pip
  run:
    - python
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - google-cloud-bigquery-core >=1.15.0,<3.0.0dev
    - google-cloud-resource-manager >=1.3.3,<3.0.0dev
    - google-cloud-storage >=1.32.0,<3.0.0dev
    - packaging >=14.3,<22.0.0dev
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.0,<5.0.0dev

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-aiplatform
  summary: Vertex AI API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
