{% set name = "google-cloud-aiplatform" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-aiplatform-{{ version }}.tar.gz
  sha256: 7768c740e455f09ea89eb53f33f8547792102d5466e8185e6ce55ba98f11a9db

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-cloud-bigquery >=1.15.0,<3.0.0dev
    - google-cloud-storage >=1.32.0,<3.0.0dev
    - packaging >=14.3
    - proto-plus >=1.15.0

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-aiplatform
  summary: Vertex AI API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
