{% set name = "google-cloud-aiplatform" %}
{% set version = "1.91.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: b14e5e52b52b6012c7dc253beab34c511fdc53c69b13f436ddb06882c1a92cd7

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv --use-pep517
  entry_points:
    - tb-gcp-uploader=google.cloud.aiplatform.tensorboard.uploader_main:run_main

requirements:
  host:
    - python
    # latest pip 25.1 is broken
    - pip 25.0
    - setuptools
    - wheel
  run:
    - python
    - google-api-core >=1.34.1,<3.0.0,!=2.0.*-2.7.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0
    - proto-plus >=1.22.3,<2.0.0
    - protobuf >=3.20.2,<7.0.0,!=4.21.0-4.21.5
    - packaging >=14.3
    - google-auth >=2.14.1,<3.0.0
    - google-cloud-storage >=1.32.0,<3.0.0
    - google-cloud-bigquery-core >=1.15.0,<4.0.0,!=3.20.0
    - google-cloud-resource-manager >=1.3.3,<3.0.0
    - shapely <3.0.0
    - pydantic <3
    - typing_extensions
    - docstring_parser <1
  run_constrained:
    - tensorboard-plugin-profile >=2.4.0,<2.18.0
    - werkzeug >=2.0.0,<4.0.0
    - tensorflow >=2.4.0,<3.0.0
    - pandas >=1.0.0
    - numpy >=1.15.0
    - lit-nlp ==0.4.0
    - explainable-ai-sdk >=1.0.0
    - google-cloud-bigquery-storage
    - pyyaml >=5.3.1,<7
    - pyarrow >=3.0.0,<8.0   # [py<311]
    - pyarrow >=10.0.1          # [py==311]
    - pyarrow >=14.0.0          # [py>311]
    - google-vizier >=0.1.6
    - docker >=5.0.3
    - starlette >=0.17.1
    - uvicorn >=0.16.0
    - requests >=2.28.1
    - requests-toolbelt <=1.0.0
    - mlflow >=1.27.0,<=2.16.0
    - ray >=2.4,<=2.42.0,!=2.5.*-2.8.*,!=2.9.0-2.9.2,!=2.10.*-2.32.*,!=2.34.*-2.41.* # [py<311]
    - immutabledict
    - google-adk >=0.0.2
    - cloudpickle >=3.0,<4.0
    - google-cloud-trace <2
    - opentelemetry-sdk <2
    - opentelemetry-exporter-gcp-trace <2
    - tqdm >=4.23.0
    - scikit-learn <1.6.0  # [py<=310]
    - scikit-learn  # [py>310]
    - jsonschema
    - ruamel.yaml
    - langchain >=0.3,<0.4
    - langchain-core >=0.3,<0.4
    - langchain-google-vertexai >=2,<3
    - langgraph >=0.2.45,<0.4
    - openinference-instrumentation-langchain >=0.1.19,< 0.2
    - ag2
    - llama-index
    - llama-index-llms-google-genai
    - sentencepiece >=0.2.0

    # There are a lot of extras for this package and they often use
    # the same packages with different pinnings. Here follow an approximation
    # with some of those commented out, and the more restrictive ones
    # enabled. To allow an easier update of these constraints, I leave
    # them there and commented out.

    # +++++++++++++++++++++++++++++++++++++++++++++++
    # profiler
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - tensorboard-plugin-profile >=2.4.0,<2.18.0
    # - werkzeug >=2.0.0,<4.0.0
    # - tensorflow >=2.4.0,<3.0.0
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # tensorboard
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - tensorflow >=2.3.0,<3.0.0  # [py<312]
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # metadata
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - pandas >=1.0.0
    # - numpy >=1.15.0
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # xai
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - tensorflow >=2.3.0,<3.0.0
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # lit
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - tensorflow >=2.3.0,<3.0.0
    # - pandas >=1.0.0
    # - lit-nlp ==0.4.0
    # - explainable-ai-sdk >=1.0.0
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # featurestore
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - google-cloud-bigquery-storage
    # - pandas >=1.0.0
    # - pyarrow >=6.0.1
    # - pandas >=1.0.0
    # - pyarrow >=6.0.1
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # pipelines
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - pyyaml >=5.3.1,<7
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # datasets
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - pyarrow >=3.0.0,<8.0   # [py<311]
    # - pyarrow >=10.0.1          # [py==311]
    # - pyarrow >=14.0.0          # [py>311]
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # vizier
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - google-vizier >=0.1.6
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # prediction
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - docker >=5.0.3
    # - fastapi >=0.71.0,<=0.114.0
    # httpx is an optional dependency of fastapi
    # - httpx >=0.23.0,<0.25.0 
    # - starlette >=0.17.1
    # - uvicorn >=0.16.0
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # endpoint
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - requests >=2.28.1
    # - requests-toolbelt <=1.0.0
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # private_endpoints
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - urllib3 >=1.21.1,<1.27
    # - requests >= 2.28.1
    # -----------------------------------------------

    # +++++++++++++++++++++++++++++++++++++++++++++++
    # autologging
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - mlflow >=1.27.0,<=2.16.0
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # ray
    # +++++++++++++++++++++++++++++++++++++++++++++++
      # Cluster only supports 2.9.3 and 2.33.0. Keep 2.4.0 for our testing environment.
      # Note that testing is submiting a job in a cluster with Ray 2.9.3 remotely.
    # - ray >=2.4,<=2.42.0,!=2.5.*-2.8.*,!=2.9.0-2.9.2,!=2.10.*-2.32.*,!=2.34.*-2.41.* # [py<311]
      # To avoid  ImportError: cannot import name 'packaging' from 'pkg.resources'
    # - setuptools <70.0.0
      # Ray Data v2.4 in Python 3.11 is broken, but got fixed in Ray v2.5.
    # - ray >=2.5,<= 2.42.0  # [py==311]
    # - google-cloud-bigquery
    # - pandas >=1.0.0
    # - pyarrow >=6.0.1
    # - immutabledict
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # adk
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - google-adk >=0.0.2
    # reasoning_engine
    # - cloudpickle >=3.0,<4.0
    # - google-cloud-trace <2
    # - opentelemetry-sdk <2
    # - opentelemetry-exporter-gcp-trace <2
    # - pydantic >=2.11.1,<3
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # agent engines
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - packaging >=24.0
    # - cloudpickle >=3.0,<4.0
    # - google-cloud-trace <2
    # - google-cloud-logging <4
    # - opentelemetry-sdk <2
    # - opentelemetry-exporter-gcp-trace <2
    # - pydantic >= 2.11.1,<3
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # evaluation
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - pandas >=1.0.0
    # - tqdm >=4.23.0
    # - scikit-learn <1.6.0  # [py<=310]
    # - scikit-learn  # [py>310]
    # - jsonschema
    # - ruamel.yaml
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # langchain
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - langchain >=0.3,<0.4
    # - langchain-core >=0.3,<0.4
    # - langchain-google-vertexai >=2,<3
    # - langgraph >=0.2.45,<0.4
    # - openinference-instrumentation-langchain >=0.1.19,< 0.2
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # ag2
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - ag2[gemini]
    # - openinference-instrumentation-autogen >=0.1.6,< 0.2
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # llama_index
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - llama-index
    # - llama-index-llms-google-genai
    # - openinference-instrumentation-llama-index >=3.0,<4.0
    # -----------------------------------------------


    # +++++++++++++++++++++++++++++++++++++++++++++++
    # tokenization
    # +++++++++++++++++++++++++++++++++++++++++++++++
    # - sentencepiece >=0.2.0
    # -----------------------------------------------

# list tests to be skipped
{% set tests_to_skip = "" %}
# test_admit for numerical approximation error
{% set tests_to_skip = tests_to_skip + " test_admit" %}
{% set tests_to_skip = tests_to_skip + " or test_function_call" %}
{% set tests_to_skip = tests_to_skip + " or test_batch_predict_job_done_create" %}
{% set tests_to_skip = tests_to_skip + " or test_function_response" %}
# skip the whole class because it is not able to mock the GCS access correctly
{% set tests_to_skip = tests_to_skip + " or TestGcsUtils" %}
# results in "gs:////" instead of "gs://""
{% set tests_to_skip = tests_to_skip + " or test_image_embedding_model_with_storage_url" %}
# requires pyarrow which will cause conflicts
{% set tests_to_skip = tests_to_skip + " or test_create_dataset_tabular_from_dataframe" %}
# wrong positional index in a list, same items
{% set tests_to_skip = tests_to_skip + " or test_get_experiment_df" %}
{% set tests_to_skip = tests_to_skip + " or test_compute_multiple_metrics" %}
# write permission error on win
{% set tests_to_skip = tests_to_skip + " or test_package_folder" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_package_file" %}  # [win]
# list test files to be ignored
{% set tests_to_ignore = "" %}
# noxfile.py#L205-L207
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/architecture" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/vertex_langchain" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/vertex_ray" %}
# they require docker, some docker functionalities
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_prediction.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_docker_utils.py" %}
# ModuleNotFoundError: No module named google-vizier
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_vizier.py" %}
# ModuleNotFoundError: No module named explainable_ai_sdk
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_logdir_loader.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_explain_lit.py" %}
# ModuleNotFoundError: No module named mlflow
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_autologging.py" %}
# ModuleNotFoundError: No module named tensorboard
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_uploader.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_uploader_utils.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_cloud_profiler.py" %}
# ModuleNotFoundError: No module named tensorflow
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_models.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_uploader_main.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_metadata_models.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_explain_saved_model_metadata_builder_tf1_test.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_explain_saved_model_metadata_builder_tf2_test.py" %}
# ModuleNotFoundError: No module named llama_index
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/vertex_llama_index/test_reasoning_engine_templates_llama_index.py" %}
# ModuleNotFoundError: No module named distutils
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_training_jobs.py" %}
# ModuleNotFoundError: No module named 'google.adk'
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/vertex_adk/test_reasoning_engine_templates_adk.py" %}
# ModuleNotFoundError: No module named 'openinference-instrumentation-autogen'
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/vertex_ag2/test_agent_engine_templates_ag2.py" %}
# this requires directly google-cloud-bigquery-storage and if we add it in the test environment
# will cause other conflicts
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_featurestores.py" %}
# flaky fails
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/unit/aiplatform/test_upload_tracker.py" %}

test:
  source_files:
    - tests/unit
  imports:
    - google
    - google.cloud
    - google.cloud.aiplatform
    - google.cloud.aiplatform_v1
    - google.cloud.aiplatform_v1beta1
    - vertexai
    - vertexai
    - vertexai._model_garden
    - vertexai.agent_engines
    - vertexai.agent_engines.templates
    - vertexai.batch_prediction
    - vertexai.caching
    - vertexai.evaluation
    - vertexai.evaluation.metrics
    - vertexai.example_stores
    - vertexai.extensions
    - vertexai.generative_models
    - vertexai.language_models
    - vertexai.model_garden
    - vertexai.preview
    - vertexai.preview.evaluation
    - vertexai.preview.rag
    - vertexai.preview.rag.utils
    - vertexai.preview.reasoning_engines
    - vertexai.preview.tuning
    - vertexai.prompts
    - vertexai.rag
    - vertexai.rag.utils
    - vertexai.reasoning_engines
    - vertexai.resources
    - vertexai.resources.preview
    - vertexai.tokenization
    - vertexai.tuning
    - vertexai.vision_models
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # tb-gcp-uploader needs tensorflow, and all these requirements, which are not all available:
    # tensorflow 2.4.1 has requirement absl-py >=0.10,<11
    # tensorflow 2.4.1 has requirement flatbuffers~=1.12.0
    # tensorflow 2.4.1 has requirement grpcio~=1.32.0
    # tensorflow 2.4.1 has requirement tensorflow-estimator<2.5.0,>=2.4.0
    # tensorflow 2.4.1 has requirement typing-extensions~=3.7.4
    # - tb-gcp-uploader --helpshort
    # Tests works locally on win, linux, and osx. More than 150,000 test needs 5 hour to build. Just skip.
    # - pytest -vv tests/unit {{ tests_to_ignore }} -k "not ({{ tests_to_skip }})"
  requires:
    # latest pip 25.1 is broken
    - pip 25.0
    - pytest
    - mock
    - pytest-asyncio
    - pytest-xdist
    - pandas
    - tqdm
    - scikit-learn
    - sentencepiece
    - pyyaml
    - pillow
    - jsonschema
    - ruamel.yaml
    - requests-toolbelt
    - ipython
    - opentelemetry-sdk <2
    - jinja2

about:
  home: https://cloud.google.com/vertex-ai/docs
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: A Python SDK for Vertex AI, a fully managed, end-to-end platform for data science and machine learning.
  description: |
    Vertex AI: Google Vertex AI is an integrated suite of machine learning tools and services
    for building and using ML models with AutoML or custom code. It offers both novices and
    experts the best workbench for the entire machine learning development lifecycle.
  doc_url: https://cloud.google.com/python/docs/reference/aiplatform/latest
  dev_url: https://github.com/googleapis/python-aiplatform
  
extra:
  recipe-maintainers:
    - xylar
  skip-lints:
    - missing_test_requirement_pip
